version: 0.0
os: linux
files:
  - source: /
    destination: /opt/lobechat
permissions:
  - object: /opt/lobechat
    owner: lobechat
    group: lobechat
    mode: 755
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
      runas: lobechat
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 300
      runas: lobechat
