version: 0.2

env:
  variables:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: "1"
    CI: "1"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - set -euxo pipefail
      - |
        if [ ! -x "$HOME/.bun/bin/bun" ]; then
          echo "Installing Bun..."
          curl -fsSL https://bun.sh/install | bash
        fi
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - export THREADS="$(nproc)"
      - export OUTPUT_FILE_TRACING_ROOT=$CODEBUILD_SRC_DIR
      - echo "OUTPUT_FILE_TRACING_ROOT=$OUTPUT_FILE_TRACING_ROOT"
      - export TOTAL_MB="$(awk '/MemTotal/ {printf "%.0f", $2/1024}' /proc/meminfo)"
      - export HEAP_MB="$(( TOTAL_MB * 80 / 100 ))"
      - if [ "$HEAP_MB" -lt 6144 ]; then export HEAP_MB=6144; fi
      - export NODE_OPTIONS="--max-old-space-size=${HEAP_MB} --max-semi-space-size=256"
      - export BUN_JOBS="${THREADS}"
      - export SWC_THREADS="${THREADS}"
      - if [ -f bun.lockb ]; then bun install --frozen-lockfile --no-progress; else bun install --no-progress; fi

  build:
    commands:
      - set -euxo pipefail
      - echo "Loading environment variables from SSM"
      - |
        REGION="us-east-1"
        SSM_PREFIX="/newswarrior/lobechat"
        NEXT_TOKEN=""
        while :; do
          if [ -z "${NEXT_TOKEN:-}" ]; then
            RESP=$(aws ssm get-parameters-by-path --path "${SSM_PREFIX}/" --with-decryption --recursive --region "$REGION" --output json)
          else
            RESP=$(aws ssm get-parameters-by-path --path "${SSM_PREFIX}/" --with-decryption --recursive --region "$REGION" --output json --starting-token "$NEXT_TOKEN")
          fi
          echo "$RESP" | jq -r '.Parameters[] | "export \(.Name|split("/")[-1])=\(.Value)"' >> /tmp/ssm_env.sh
          NEXT_TOKEN=$(echo "$RESP" | jq -r '.NextToken // empty')
          [ -z "$NEXT_TOKEN" ] && break
        done
        source /tmp/ssm_env.sh
      - echo "Running Next.js build (standalone mode)"
      - export OUTPUT_FILE_TRACING_ROOT=$CODEBUILD_SRC_DIR
      - bun run prebuild || true
      - npx next build
      - bun run postbuild || true
      - |
        if [ ! -f ".next/standalone/server.js" ]; then
          echo "❌ ERROR: .next/standalone/server.js not found. Check next.config.js has output: 'standalone'" >&2
          exit 1
        fi

artifacts:
  files:
    - .next/standalone/**/*
    - .next/static/**/*
    - public/**/*
    - package.json
    - bun.lockb
    - appspec.yml
    - deploy/**/*
  discard-paths: no

cache:
  paths:
    - '~/.bun/**/*'
    - '.next/cache/**/*'
